/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.awt.Font;
import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.JOptionPane;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Sajjad
 */
public class AgentInfo extends javax.swing.JFrame {

    private String nuvarandeAnvandare;
    private static InfDB idb;
    private int filterTyp;
    private String filterFraga;

    private String startDatum;
    private String slutDatum;

    /**
     * Creates new form Administrator
     */
    public AgentInfo(InfDB idb, String nuvarandeAnvandare) {

        initComponents();
        this.idb = idb;
        this.nuvarandeAnvandare = nuvarandeAnvandare;
        tabbedPane.setSelectedIndex(0);
        HashMap<String, String> agentInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblAlien = new javax.swing.JLabel();
        lblMinSida = new javax.swing.JLabel();
        lblUtrustning = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlAgent = new javax.swing.JPanel();
        cbFilter1 = new javax.swing.JComboBox<>();
        cbFilter2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultat = new javax.swing.JTextArea();
        andraAgentInfo = new javax.swing.JButton();
        btnRegistreraAgent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setPreferredSize(new java.awt.Dimension(800, 80));

        lblAlien.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblAlien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlien.setText("Alien");
        lblAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlienMouseClicked(evt);
            }
        });

        lblMinSida.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblMinSida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinSida.setText("Min Sida");
        lblMinSida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinSidaMouseClicked(evt);
            }
        });

        lblUtrustning.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblUtrustning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtrustning.setText("Utrusning");
        lblUtrustning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUtrustningMouseClicked(evt);
            }
        });

        lblOmrade.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblOmrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOmrade.setText("Omrade");
        lblOmrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOmradeMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agent");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblMinSida, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(lblAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(lblUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustning)
                    .addComponent(lblMinSida)
                    .addComponent(lblAlien)
                    .addComponent(lblOmrade)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        cbFilter1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Namn", "Alla", "Sortera efter Anställningsdatum (nyast först)" }));
        cbFilter1.setPreferredSize(new java.awt.Dimension(200, 22));
        cbFilter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilter1ActionPerformed(evt);
            }
        });

        cbFilter2.setMinimumSize(new java.awt.Dimension(200, 22));
        cbFilter2.setPreferredSize(new java.awt.Dimension(200, 22));
        cbFilter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilter2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Sökfilter 1:");

        jLabel6.setText("Sökfilter 2:");

        txtAreaResultat.setColumns(20);
        txtAreaResultat.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultat);

        andraAgentInfo.setText("Ändra Information Om En Agent");
        andraAgentInfo.setMaximumSize(new java.awt.Dimension(200, 22));
        andraAgentInfo.setMinimumSize(new java.awt.Dimension(200, 22));
        andraAgentInfo.setPreferredSize(new java.awt.Dimension(200, 22));
        andraAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraAgentInfoActionPerformed(evt);
            }
        });

        btnRegistreraAgent.setText("Registrera Ny Agent");
        btnRegistreraAgent.setMaximumSize(new java.awt.Dimension(200, 22));
        btnRegistreraAgent.setMinimumSize(new java.awt.Dimension(200, 22));
        btnRegistreraAgent.setPreferredSize(new java.awt.Dimension(200, 22));
        btnRegistreraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraAgentActionPerformed(evt);
            }
        });

        jButton1.setText("Ta Bort Alien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgentLayout = new javax.swing.GroupLayout(pnlAgent);
        pnlAgent.setLayout(pnlAgentLayout);
        pnlAgentLayout.setHorizontalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgentLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgentLayout.createSequentialGroup()
                        .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFilter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1)
                    .addGroup(pnlAgentLayout.createSequentialGroup()
                        .addComponent(btnRegistreraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(andraAgentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        pnlAgentLayout.setVerticalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgentLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgentLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilter2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgentLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilter1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraAgentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistreraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        tabbedPane.addTab("tab1", pnlAgent);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilter1ActionPerformed
        int filter1 = cbFilter1.getSelectedIndex();
        String kolumn = "";
        String tabel = "";

        switch (filter1) {
            case 1:
                cbFilter2.removeAllItems();
                txtAreaResultat.setText("");
                kolumn = "Namn";
                tabel = "Agent";
                cbFilter2.addItem("Välj namn");
                gorFetchColumn(kolumn, tabel, cbFilter2);
                cbFilter2.requestFocus();
                break;
            case 2:
                cbFilter2.removeAllItems();
                filterFraga = "select * from Agent";
                gorFetchRows(txtAreaResultat);
                break;
            case 3:
                cbFilter2.removeAllItems();
                filterFraga = "select * from agent order by anstallningsdatum desc;";
                gorFetchRows(txtAreaResultat);
                break;
            default:
                cbFilter2.removeAllItems();
                break;
        }
    }//GEN-LAST:event_cbFilter1ActionPerformed

    private void cbFilter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilter2ActionPerformed
        if (cbFilter2.getSelectedIndex() > 0) {
            try {
                filterFraga = "SELECT * FROM agent where namn= '" + cbFilter2.getSelectedItem().toString() + "'";
                gorFetchRows(txtAreaResultat);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cbFilter2ActionPerformed

    private void andraAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraAgentInfoActionPerformed
        new AndraAgentInfo(idb).setVisible(true);
    }//GEN-LAST:event_andraAgentInfoActionPerformed

    private void btnRegistreraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraAgentActionPerformed
        new RegistreraNyAgent(idb).setVisible(true);
    }//GEN-LAST:event_btnRegistreraAgentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TaBortAgent(idb, nuvarandeAnvandare).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblMinSidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinSidaMouseClicked
        new Administrator(idb, nuvarandeAnvandare, "MinSida").setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMinSidaMouseClicked

    private void lblAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlienMouseClicked
        new Administrator(idb, nuvarandeAnvandare, "Alien").setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAlienMouseClicked

    private void lblUtrustningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtrustningMouseClicked
        new Administrator(idb, nuvarandeAnvandare, "Utrustning").setVisible(true);
        dispose();
    }//GEN-LAST:event_lblUtrustningMouseClicked

    private void lblOmradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOmradeMouseClicked
        new Administrator(idb, nuvarandeAnvandare, "Omrade").setVisible(true);
        dispose();
    }//GEN-LAST:event_lblOmradeMouseClicked

    private void gorFetchColumn(String kolumn, String tabel, JComboBox comboBox) {
        ArrayList<String> allaAlternativ;
        String fraga = "Select " + kolumn + " from " + tabel;

        try {
            allaAlternativ = idb.fetchColumn(fraga);
            for (String alternativ : allaAlternativ) {
                comboBox.addItem(alternativ);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }

    private void gorFetchRows(JTextArea textArea) {
        txtAreaResultat.setText("");
        ArrayList<HashMap<String, String>> allaAgenter;

        try {
            textArea.append("ID:" + "\t");
            textArea.append("Namn:" + "\t");
            textArea.append("Telefon:" + "\t");
            textArea.append("Anställningsdatum:" + "\t");
            textArea.append("Administratör:" + "\t");
            textArea.append("Område:" + "\n \n");

            allaAgenter = idb.fetchRows(filterFraga);

            for (HashMap<String, String> agent : allaAgenter) {
                textArea.append(agent.get("Agent_ID") + "\t");
                textArea.append(agent.get("Namn") + "\t");
                textArea.append(agent.get("Telefon") + "\t");
                textArea.append(agent.get("Anstallningsdatum") + "\t \t");
                textArea.append(agent.get("Administrator") + "\t");
                textArea.append(agent.get("Omrade") + "\n");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andraAgentInfo;
    private javax.swing.JButton btnRegistreraAgent;
    private javax.swing.JComboBox<String> cbFilter1;
    private javax.swing.JComboBox<String> cbFilter2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlien;
    private javax.swing.JLabel lblMinSida;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JPanel pnlAgent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextArea txtAreaResultat;
    // End of variables declaration//GEN-END:variables
}
