/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Sajjad
 */
public class Agent extends javax.swing.JFrame {

    private String nuvarandeAnvandare;
    private static InfDB idb;

    /**
     * Creates new form Agent
     */
    public Agent() {
        initComponents();

        nuvarandeAnvandare = HuvudFonster.getNuvarandeAnvandare();
        idb = HuvudFonster.getdb();
        tabbedPane.setSelectedIndex(1);
        HashMap<String, String> agentInfo;

        try {
            agentInfo = idb.fetchRow("SELECT Telefon, Anstallningsdatum, Administrator FROM agent where namn ='" + nuvarandeAnvandare + "'");

            lblNamn.setText(nuvarandeAnvandare);
            lblDBTelefon.setText(agentInfo.get("Telefon") + "\t\t");
            lblDBAnstallningsdatum.setText(agentInfo.get("Anstallningsdatum") + "\t");
            lblDBAdministrator.setText(agentInfo.get("Administrator") + "\t");

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "databasfel!");
            System.out.println("/////////////" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblAlien = new javax.swing.JLabel();
        lblMinSida = new javax.swing.JLabel();
        lblUtrustning = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlAlien = new javax.swing.JPanel();
        pnlMinSida = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAnstallningsdatum = new javax.swing.JLabel();
        lblAdministrator = new javax.swing.JLabel();
        lblDBTelefon = new javax.swing.JLabel();
        lblDBAnstallningsdatum = new javax.swing.JLabel();
        lblDBAdministrator = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        pnlUrustning = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblAlien.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblAlien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlien.setText("Alien");
        lblAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlienMouseClicked(evt);
            }
        });

        lblMinSida.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblMinSida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinSida.setText("Min Sida");
        lblMinSida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinSidaMouseClicked(evt);
            }
        });

        lblUtrustning.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblUtrustning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtrustning.setText("Utrusning");
        lblUtrustning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUtrustningMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblAlien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(lblMinSida)
                .addGap(264, 264, 264)
                .addComponent(lblUtrustning)
                .addGap(30, 30, 30))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustning)
                    .addComponent(lblMinSida)
                    .addComponent(lblAlien))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        pnlAlien.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAlienLayout = new javax.swing.GroupLayout(pnlAlien);
        pnlAlien.setLayout(pnlAlienLayout);
        pnlAlienLayout.setHorizontalGroup(
            pnlAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlAlienLayout.setVerticalGroup(
            pnlAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        tabbedPane.addTab("tab1", pnlAlien);

        pnlMinSida.setBackground(new java.awt.Color(255, 255, 255));

        lblNamn.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        lblNamn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamn.setText("Namn");

        lblTelefon.setText("Telefon");

        lblAnstallningsdatum.setText("Anställningsdatum");

        lblAdministrator.setText("Adminstratör");

        lblDBTelefon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblDBAnstallningsdatum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblDBAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnAndraLosenord.setText("Ändra lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");

        javax.swing.GroupLayout pnlMinSidaLayout = new javax.swing.GroupLayout(pnlMinSida);
        pnlMinSida.setLayout(pnlMinSidaLayout);
        pnlMinSidaLayout.setHorizontalGroup(
            pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinSidaLayout.createSequentialGroup()
                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMinSidaLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMinSidaLayout.createSequentialGroup()
                                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDBTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefon))
                                .addGap(49, 49, 49)
                                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDBAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAnstallningsdatum))
                                .addGap(92, 92, 92)
                                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdministrator)
                                    .addComponent(lblDBAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlMinSidaLayout.createSequentialGroup()
                                .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMinSidaLayout.setVerticalGroup(
            pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinSidaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNamn)
                .addGap(82, 82, 82)
                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(lblAdministrator)
                    .addComponent(lblAnstallningsdatum))
                .addGap(18, 18, 18)
                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDBAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(pnlMinSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        tabbedPane.addTab("tab2", pnlMinSida);

        pnlUrustning.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlUrustningLayout = new javax.swing.GroupLayout(pnlUrustning);
        pnlUrustning.setLayout(pnlUrustningLayout);
        pnlUrustningLayout.setHorizontalGroup(
            pnlUrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlUrustningLayout.setVerticalGroup(
            pnlUrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        tabbedPane.addTab("tab3", pnlUrustning);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlienMouseClicked
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_lblAlienMouseClicked

    private void lblMinSidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinSidaMouseClicked
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_lblMinSidaMouseClicked

    private void lblUtrustningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtrustningMouseClicked
        tabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_lblUtrustningMouseClicked

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        AndraLosenord andraLosenord = new AndraLosenord();
        andraLosenord.setVisible(true);
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JLabel lblAdministrator;
    private javax.swing.JLabel lblAlien;
    private javax.swing.JLabel lblAnstallningsdatum;
    private javax.swing.JLabel lblDBAdministrator;
    private javax.swing.JLabel lblDBAnstallningsdatum;
    private javax.swing.JLabel lblDBTelefon;
    private javax.swing.JLabel lblMinSida;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JPanel pnlAlien;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMinSida;
    private javax.swing.JPanel pnlUrustning;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
