/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class Alien extends javax.swing.JFrame {

    private String nuvarandeAnvandare;
    private static InfDB idb;

    /**
     * Creates new form Alien
     */
    public Alien(InfDB idb, String nuvarandeAnvandare) {
        initComponents();
        this.idb = idb;
        this.nuvarandeAnvandare = nuvarandeAnvandare;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Alien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndralosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndralosenordActionPerformed
        new AndraLosenord(idb, nuvarandeAnvandare).setVisible(true);
    }//GEN-LAST:event_btnAndralosenordActionPerformed


    private void btnAnsvarigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsvarigActionPerformed
        
        try {
            String infoAgent = idb.fetchSingle("SELECT namn from agent where agent_id =(select ansvarig_agent from alien where namn ='" + nuvarandeAnvandare + "')");
            JOptionPane.showMessageDialog(null, "Ditt ansvarig agent heter: "+ infoAgent);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            //System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAnsvarigActionPerformed


    private void btnLoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggautActionPerformed
        new HuvudFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoggautActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
