/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class AndraAgentInfo extends javax.swing.JFrame {

    private static InfDB idb;
    private int sida = 1;

    /**
     * Creates new form AndraAgentInfo
     */
    public AndraAgentInfo(InfDB idb) {
        initComponents();
        this.idb = idb;
        gorFetchColumn("Namn", "Agent", cbValjAgent);
        gorFetchColumn("Benamning", "Omrade", cbOmrade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cbValjAgent = new javax.swing.JComboBox<>();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbOmrade = new javax.swing.JComboBox<>();
        txtLosenord = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        cbBehorighet = new javax.swing.JComboBox<>();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbValjAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cbValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 97));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Namn:");

        txtNamn.setMinimumSize(new java.awt.Dimension(64, 30));
        txtNamn.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lösenord:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefon:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Område:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Administratör:");

        cbOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj" }));
        cbOmrade.setMinimumSize(new java.awt.Dimension(72, 30));
        cbOmrade.setPreferredSize(new java.awt.Dimension(72, 30));

        txtLosenord.setMinimumSize(new java.awt.Dimension(64, 30));
        txtLosenord.setPreferredSize(new java.awt.Dimension(64, 30));

        txtTelefon.setMinimumSize(new java.awt.Dimension(64, 30));
        txtTelefon.setPreferredSize(new java.awt.Dimension(64, 30));

        cbBehorighet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj", "JA", "NEJ" }));
        cbBehorighet.setMinimumSize(new java.awt.Dimension(72, 30));
        cbBehorighet.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab1", jPanel1);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, 290));

        btnSpara.setText("Spara ändringar");
        btnSpara.setPreferredSize(new java.awt.Dimension(75, 30));
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpara, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 390, 330, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        String agent = "";

        if (cbValjAgent.getSelectedIndex() > 0) {
            agent = cbValjAgent.getSelectedItem().toString();

            String sqlQuery = "update agent set ";

            if (!(txtNamn.getText().isEmpty())) {
                String namn = txtNamn.getText();
                sqlQuery = sqlQuery + "Namn= '" + namn + "'";
            } else {
                sqlQuery = sqlQuery + "Namn= '" + agent + "'";
            }
            if (!(txtLosenord.getText().isEmpty())) {
                String losenord = txtLosenord.getText();
                sqlQuery = sqlQuery + ", Losenord= '" + losenord + "'";
            }
            if (!(txtTelefon.getText().isEmpty())) {
                String telefon = txtTelefon.getText();
                sqlQuery = sqlQuery + ", Telefon= '" + telefon + "'";
            }
            if (cbOmrade.getSelectedIndex() > 0) {
                try {
                    String omradeID = idb.fetchSingle("Select Omrades_id from Omrade where Benamning ='" + cbOmrade.getSelectedItem().toString() + "'");
                    sqlQuery = sqlQuery + ", Omrade= " + omradeID;
                } catch (InfException ex) {
                    System.out.println(ex.getMessage());
                }
            }
            if (cbBehorighet.getSelectedIndex() > 0) {
                sqlQuery = sqlQuery + ", Administrator= '" + cbBehorighet.getSelectedItem().toString().substring(0, 1) + "'";
            } else {
                try {
                    String behorighet = idb.fetchSingle("SELECT Administrator FROM agent where namn='" + agent + "'");
                    sqlQuery = sqlQuery + ", Administrator= '" + behorighet + "'";
                } catch (InfException ex) {
                    JOptionPane.showMessageDialog(null, "Databasfel!");
                    System.out.println(ex.getMessage());
                }

            }

            sqlQuery = sqlQuery + " where namn='" + agent + "'";
            System.out.println(sqlQuery);

            try {
                idb.update(sqlQuery);
                JOptionPane.showMessageDialog(null, "Ändringar har sparats");
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Databasfel! update");
                System.out.println(ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Du måste först välja vems information du vill ändra");
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void gorFetchColumn(String kolumn, String tabel, JComboBox comboBox) {
        ArrayList<String> allaAlternativ;
        String fraga = "Select " + kolumn + " from " + tabel;

        try {
            allaAlternativ = idb.fetchColumn(fraga);
            for (String alternativ : allaAlternativ) {
                comboBox.addItem(alternativ);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JComboBox<String> cbBehorighet;
    private javax.swing.JComboBox<String> cbOmrade;
    private javax.swing.JComboBox<String> cbValjAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
