/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.JOptionPane;

/**
 *
 * @author Sajjad
 */
public class HuvudFonster extends javax.swing.JFrame {

    private static InfDB idb;
    private String nuvarandeAnvandare;

    /**
     * Creates new form HuvudFonster
     */
    public HuvudFonster(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoggaIn = new javax.swing.JLabel();
        lblAnvandernamn = new javax.swing.JLabel();
        txtAnvandernamn = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        pswLosenord = new javax.swing.JPasswordField();
        btnLoggaIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Men In Black");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(25, 25, 25));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        lblLoggaIn.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        lblLoggaIn.setForeground(new java.awt.Color(102, 102, 102));
        lblLoggaIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggaIn.setText("LOGGA IN");
        lblLoggaIn.setAlignmentY(0.0F);

        lblAnvandernamn.setForeground(new java.awt.Color(102, 102, 102));
        lblAnvandernamn.setText("Användernamn");

        txtAnvandernamn.setSelectionColor(new java.awt.Color(241, 80, 37));

        lblLosenord.setForeground(new java.awt.Color(102, 102, 102));
        lblLosenord.setText("Lösenord");

        pswLosenord.setSelectionColor(new java.awt.Color(241, 80, 37));

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Men In Black");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAnvandernamn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnvandernamn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblAnvandernamn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnvandernamn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        nuvarandeAnvandare = txtAnvandernamn.getText().toUpperCase();
        String losenord = new String(pswLosenord.getPassword());
        boolean isAgent = false;

        try {
            if (nuvarandeAnvandare.substring(0, 5).equals("AGENT")) {
                isAgent = true;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        if (isAgent && isPSWright("Agent", nuvarandeAnvandare, losenord)) {
            try {
                String isAdmin = idb.fetchSingle("SELECT administrator FROM agent where namn='" + nuvarandeAnvandare + "'");
                if (isAdmin.equals("J")) {
                    new Administrator(idb, nuvarandeAnvandare,"MinSida").setVisible(true);
                } else {
                    new Agent(idb, nuvarandeAnvandare).setVisible(true);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Databasfel 1!");
                System.out.println(e.getMessage());
            }
            dispose();
        } else if (!isAgent) {
            if (isPSWright("Alien", nuvarandeAnvandare, losenord)) {
                new Alien(idb, nuvarandeAnvandare).setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_btnLoggaInActionPerformed

    private boolean isPSWright(String tabel, String anvandare, String losenord) {
        boolean isRight = false;
        try {
            String dbLosenord = idb.fetchSingle("Select losenord from " + tabel + " where Namn='" + anvandare + "'");
            if (losenord.equals(dbLosenord)) {
                isRight = true;
            } else {
                JOptionPane.showMessageDialog(null, "Felaktigt användarnamn eller lösenord.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel 2!");
            System.out.println(e.getMessage());
        }
        return isRight;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnvandernamn;
    private javax.swing.JLabel lblLoggaIn;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JPasswordField pswLosenord;
    private javax.swing.JTextField txtAnvandernamn;
    // End of variables declaration//GEN-END:variables
}
