/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class RegistreraNyAlien extends javax.swing.JFrame {

    private static InfDB idb;
    private int sida = 1;

    /**
     * Creates new form RegistreraNyAlien
     */
    public RegistreraNyAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        gorFetchColumn("Benamning", "Plats", cbPlats);
        gorFetchColumn("Namn", "Agent", cbAnsvarigAgent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        REGISTRERANYALIEN = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbPlats = new javax.swing.JComboBox<>();
        txtLosenord = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        cbAnsvarigAgent = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRasDetalj = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbRas = new javax.swing.JComboBox<>();
        txtRasDetalj = new javax.swing.JTextField();
        btnNasta = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 55));

        REGISTRERANYALIEN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        REGISTRERANYALIEN.setText("REGISTRERA NY ALIEN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REGISTRERANYALIEN, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REGISTRERANYALIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 57));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Namn: *");

        txtNamn.setMinimumSize(new java.awt.Dimension(64, 30));
        txtNamn.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lösenord:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefon:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Plats: *");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Ansvarig Agent: *");

        cbPlats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj" }));
        cbPlats.setMinimumSize(new java.awt.Dimension(72, 30));
        cbPlats.setPreferredSize(new java.awt.Dimension(72, 30));

        txtLosenord.setMinimumSize(new java.awt.Dimension(64, 30));
        txtLosenord.setPreferredSize(new java.awt.Dimension(64, 30));

        txtTelefon.setMinimumSize(new java.awt.Dimension(64, 30));
        txtTelefon.setPreferredSize(new java.awt.Dimension(64, 30));

        cbAnsvarigAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj" }));
        cbAnsvarigAgent.setMinimumSize(new java.awt.Dimension(72, 30));
        cbAnsvarigAgent.setPreferredSize(new java.awt.Dimension(72, 30));

        txtID.setMinimumSize(new java.awt.Dimension(64, 30));
        txtID.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("ID: *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab1", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRasDetalj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRasDetalj.setText("Detalj:");
        jPanel2.add(lblRasDetalj, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 69, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ras: *");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, -1, -1));

        cbRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj", "Squid", "Worm", "Boglodite" }));
        cbRas.setMinimumSize(new java.awt.Dimension(72, 30));
        cbRas.setPreferredSize(new java.awt.Dimension(72, 30));
        cbRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRasActionPerformed(evt);
            }
        });
        jPanel2.add(cbRas, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 19, 190, 28));

        txtRasDetalj.setEnabled(false);
        txtRasDetalj.setMinimumSize(new java.awt.Dimension(64, 30));
        txtRasDetalj.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel2.add(txtRasDetalj, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 65, 190, -1));

        tabbedPane.addTab("tab1", jPanel2);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 34, 350, 360));

        btnNasta.setText("Nästa");
        btnNasta.setPreferredSize(new java.awt.Dimension(75, 30));
        btnNasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNastaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, -1));

        btnLaggTill.setText("Lägg till");
        btnLaggTill.setEnabled(false);
        btnLaggTill.setPreferredSize(new java.awt.Dimension(75, 30));
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaggTill, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 130, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNastaActionPerformed

        if (sida == 1) {
            tabbedPane.setSelectedIndex(1);
            btnNasta.setText("Tillbaka");
            btnLaggTill.setEnabled(true);
            sida = 2;
        } else {
            tabbedPane.setSelectedIndex(0);
            btnNasta.setText("Nästa");
            btnLaggTill.setEnabled(false);
            sida = 1;
        }
    }//GEN-LAST:event_btnNastaActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed

        String sqlQuery = "Insert into Alien values(";
        String sqlQueryRas = "";
        boolean isOkej = true;

        if (!(txtID.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtID.getText() + ", '" + java.time.LocalDate.now() + "', '";
        } else {
            isOkej = false;
        }
        if (!(txtLosenord.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtLosenord.getText() + "', '";
        } else {
            sqlQuery = sqlQuery + "','";
        }
        if (!(txtNamn.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtNamn.getText() + "', '";
        } else {
            isOkej = false;
        }
        if (!(txtTelefon.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtTelefon.getText() + "', ";
        } else {
            sqlQuery = sqlQuery + "', ";
        }
        if (cbPlats.getSelectedIndex() > 0) {
            try {
                String platsID = idb.fetchSingle("Select plats_ID from plats where Benamning ='" + cbPlats.getSelectedItem().toString() + "'");
                sqlQuery = sqlQuery + platsID + ", ";
            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            isOkej = false;
        }
        if (cbAnsvarigAgent.getSelectedIndex() > 0) {
            try {
                String agentID = idb.fetchSingle("Select agent_ID from agent where namn ='" + cbAnsvarigAgent.getSelectedItem().toString() + "'");
                sqlQuery = sqlQuery + agentID + ")";
            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }

        } else {
            isOkej = false;
        }

        switch (cbRas.getSelectedIndex()) {
            case 1:
                sqlQueryRas = "insert into Squid VALUES(" + txtID.getText() + "," + txtRasDetalj.getText() + ")";
                break;
            case 2:
                sqlQueryRas = "insert into Worm VALUES(" + txtID.getText() + ")";
                break;
            case 3:
                sqlQueryRas = "insert into Boglodite VALUES(" + txtID.getText() + "," + txtRasDetalj.getText() + ")";
                break;
            default:
                isOkej = false;
                break;
        }

        System.out.println(sqlQuery);

        if (isOkej) {
            try {
                idb.insert(sqlQuery);
                idb.insert(sqlQueryRas);
                JOptionPane.showMessageDialog(null, "Alien har registrerats");
                dispose();
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Databasfel! insert a");
                System.out.println(ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fält markerade med * är obligatoriska och måste fyllas i");
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void cbRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRasActionPerformed
        switch (cbRas.getSelectedIndex()) {
            case 1:
                lblRasDetalj.setText("Antal armar:");
                txtRasDetalj.setEnabled(true);
                break;
            case 2:
                lblRasDetalj.setText("Detalj:");
                txtRasDetalj.setEnabled(false);
                break;
            case 3:
                lblRasDetalj.setText("Antal boogies:");
                txtRasDetalj.setEnabled(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbRasActionPerformed

    private void gorFetchColumn(String kolumn, String tabel, JComboBox comboBox) {
        ArrayList<String> allaAlternativ;
        String fraga = "Select " + kolumn + " from " + tabel;

        try {
            allaAlternativ = idb.fetchColumn(fraga);
            for (String alternativ : allaAlternativ) {
                comboBox.addItem(alternativ);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REGISTRERANYALIEN;
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnNasta;
    private javax.swing.JComboBox<String> cbAnsvarigAgent;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JComboBox<String> cbRas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblRasDetalj;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtRasDetalj;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
