/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class RegistreraNyUtrustning extends javax.swing.JFrame {

    private static InfDB idb;
    private int sida = 1;

    /**
     * Creates new form RegistreraNyUtrustning
     */
    public RegistreraNyUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbValjTyp = new javax.swing.JComboBox<>();
        pnlFalt = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtDetalj = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblDetalj = new javax.swing.JLabel();
        btnLaggTill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 470));
        setResizable(false);

        cbValjTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj typ av utrustning", "Vapen", "Teknik", "Kommunikation" }));
        cbValjTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjTypActionPerformed(evt);
            }
        });

        pnlFalt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pnlFalt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setEnabled(false);
        txtID.setMinimumSize(new java.awt.Dimension(64, 30));
        txtID.setPreferredSize(new java.awt.Dimension(64, 30));
        pnlFalt.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 19, 220, -1));

        txtNamn.setEnabled(false);
        txtNamn.setMinimumSize(new java.awt.Dimension(64, 30));
        txtNamn.setPreferredSize(new java.awt.Dimension(64, 30));
        pnlFalt.add(txtNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 67, 220, -1));

        txtDetalj.setEnabled(false);
        txtDetalj.setMinimumSize(new java.awt.Dimension(64, 30));
        txtDetalj.setPreferredSize(new java.awt.Dimension(64, 30));
        pnlFalt.add(txtDetalj, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 115, 220, -1));

        lblID.setText("ID: *");
        pnlFalt.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 26, -1, -1));

        lblNamn.setText("Namn: *");
        pnlFalt.add(lblNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 74, -1, -1));

        lblDetalj.setText("Detalj:");
        pnlFalt.add(lblDetalj, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 122, -1, -1));

        btnLaggTill.setText("Lägg till");
        btnLaggTill.setPreferredSize(new java.awt.Dimension(75, 30));
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbValjTyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaggTill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFalt, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cbValjTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(pnlFalt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed

        String sqlQuery = "Insert into Utrustning values(";
        String sqlQueryTyp = "";
        String kolumnDetalj = "";
        boolean isOkej = true;

        if (!(txtID.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtID.getText() + ", '";
        } else {
            isOkej = false;
        }
        if (!(txtNamn.getText().isEmpty())) {
            sqlQuery = sqlQuery + txtNamn.getText() + "')";
        } else {
            isOkej = false;
        }

        switch (cbValjTyp.getSelectedIndex()) {
            case 1:
                sqlQueryTyp = "insert into Vapen VALUES(" + txtID.getText() + ", " + txtDetalj.getText() + ")";
                break;
            case 2:
                sqlQueryTyp = "insert into Teknik VALUES(" + txtID.getText() + ", '" + txtDetalj.getText() + "')";
                break;
            case 3:
                sqlQueryTyp = "insert into Kommunikation VALUES(" + txtID.getText() + ", '" + txtDetalj.getText() + "')";
                break;
            default:
                isOkej = false;
                break;
        }

        if (isOkej) {
            try {
                idb.insert(sqlQuery);
                idb.insert(sqlQueryTyp);
                JOptionPane.showMessageDialog(null, "Utrustning har registrerats");
                dispose();
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Databasfel! insert a");
                System.out.println(ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fält markerade med * är obligatoriska och måste fyllas i");
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void cbValjTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjTypActionPerformed
        switch (cbValjTyp.getSelectedIndex()) {
            case 1:
                lblDetalj.setText("Kaliber:");
                setFaltenEnabled();
                break;
            case 2:
                lblDetalj.setText("Kraftkälla:");
                setFaltenEnabled();
                break;
            case 3:
                lblDetalj.setText("Överföringsteknik:");
                setFaltenEnabled();
                break;
            default:
                lblDetalj.setText("Detalj:");
                setFaltenDisabled();
                break;
        }
    }//GEN-LAST:event_cbValjTypActionPerformed

    private void setFaltenEnabled() {
        txtID.setEnabled(true);
        txtNamn.setEnabled(true);
        txtDetalj.setEnabled(true);
    }

    private void setFaltenDisabled() {
        txtID.setEnabled(false);
        txtNamn.setEnabled(false);
        txtDetalj.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JComboBox<String> cbValjTyp;
    private javax.swing.JLabel lblDetalj;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JPanel pnlFalt;
    private javax.swing.JTextField txtDetalj;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNamn;
    // End of variables declaration//GEN-END:variables
}
