/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class TaBortAgent extends javax.swing.JFrame {

    private String nuvarandeAnvandare;
    private static InfDB idb;
    private boolean okTaBort;

    /**
     * Creates new form TaBortAgent
     */
    public TaBortAgent(InfDB idb, String nuvarandeAnvandare) {
        initComponents();
        this.idb = idb;
        this.nuvarandeAnvandare = nuvarandeAnvandare;
        gorFetchColumn("Namn", "Agent", cbAgent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAgent = new javax.swing.JComboBox<>();
        pwdLosenord = new javax.swing.JPasswordField();
        lblLosenord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj" }));
        cbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgentActionPerformed(evt);
            }
        });

        lblLosenord.setText("Ditt lösenord:");

        jLabel2.setText("Alien:");

        btnTaBort.setText("Ta bort agent");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLosenord)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdLosenord)
                    .addComponent(btnTaBort, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        if (cbAgent.getSelectedIndex() >= 0) {
            String agent = cbAgent.getSelectedItem().toString();
            String losenord = new String(pwdLosenord.getPassword());

            try {
                String dbLosenord = idb.fetchSingle("Select losenord from agent where Namn='" + nuvarandeAnvandare + "'");
                if (losenord.equals(dbLosenord)) {
                    try {
                        String agentID = idb.fetchSingle("Select Agent_ID from agent where namn ='" + agent + "'");
                        idb.delete("Delete from kontorschef where Agent_ID=" + agentID);
                        idb.delete("Delete from omradeschef where Agent_ID=" + agentID);
                        idb.delete("Delete from Innehar_fordon where Agent_ID=" + agentID);
                        idb.delete("Delete from innehar_utrustning where Agent_ID=" + agentID);
                        idb.delete("Delete from Agent where namn='" + agent + "'");
                        JOptionPane.showMessageDialog(null, "Agent togs bort");
                        dispose();
                    } catch (InfException e) {
                        JOptionPane.showMessageDialog(null, "Databasfel!");
                        System.out.println(e.getMessage());
                    }

                } else {
                    //JOptionPane.showMessageDialog(rootPane, "Ange korrekt lösenord.", "", HEIGHT);
                    lblLosenord.setForeground(Color.red);
                }
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Databasfel!");
                System.out.println(ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Välj agent!");
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void cbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgentActionPerformed
        String agent = cbAgent.getSelectedItem().toString();

        try {
            ArrayList<HashMap<String, String>> allaAlien;
            String agentID = idb.fetchSingle("Select Agent_ID from agent where namn ='" + agent + "'");
            allaAlien = idb.fetchRows("select * from alien where ansvarig_agent=" + agentID);

            if (!allaAlien.isEmpty()) {
                new TilldelaAnsvaret(idb, agent).setVisible(true);
                cbAgent.setSelectedIndex(-1);
                cbAgent.requestFocus();
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cbAgentActionPerformed

    private void gorFetchColumn(String kolumn, String tabel, JComboBox comboBox) {
        ArrayList<String> allaAlternativ;
        String fraga = "Select " + kolumn + " from " + tabel;

        try {
            allaAlternativ = idb.fetchColumn(fraga);
            for (String alternativ : allaAlternativ) {
                comboBox.addItem(alternativ);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel! tb agent");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cbAgent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JPasswordField pwdLosenord;
    // End of variables declaration//GEN-END:variables
}
