/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Sajjad
 */
public class TilldelaAnsvaret extends javax.swing.JFrame {

    private static InfDB idb;
    private String agent;
    private String valdAgent;

    /**
     * Creates new form TilldelaAnsvaret
     */
    public TilldelaAnsvaret(InfDB idb, String agent) {
        initComponents();

        this.idb = idb;
        this.agent = agent;
        gorFetchColumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoRad1 = new javax.swing.JLabel();
        lblInfoRad2 = new javax.swing.JLabel();
        cbValjAgent = new javax.swing.JComboBox<>();
        btnAvbryt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        lblInfoRad1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblInfoRad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoRad1.setText("Agenten du vill ta bort har ansvar för alien.");

        lblInfoRad2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblInfoRad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoRad2.setText("Vill du tilldela ansvaret till en annan agent?");

        cbValjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjAgentActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoRad1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoRad2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbValjAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAvbryt, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInfoRad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoRad2)
                .addGap(33, 33, 33)
                .addComponent(cbValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvbryt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjAgentActionPerformed
        try {
            String agentID = idb.fetchSingle("Select Agent_ID from agent where namn ='" + cbValjAgent.getSelectedItem().toString() + "'");
            String notAgentID = idb.fetchSingle("Select Agent_ID from agent where namn ='" + agent + "'");
            idb.update("Update alien set ansvarig_agent =" + agentID + " where ansvarig_agent =" + notAgentID);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_cbValjAgentActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        dispose();
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void gorFetchColumn() {
        ArrayList<String> allaAlternativ;

        try {
            allaAlternativ = idb.fetchColumn("Select Namn from Agent where namn !='" + agent + "'");
            for (String alternativ : allaAlternativ) {
                cbValjAgent.addItem(alternativ);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("////" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JComboBox<String> cbValjAgent;
    private javax.swing.JLabel lblInfoRad1;
    private javax.swing.JLabel lblInfoRad2;
    // End of variables declaration//GEN-END:variables
}
